In [15]:
# Question 1
import numpy as np

c = np.array([0.5 , 1.2 , 0.8 , 0.3])
print(c)

[0.5 1.2 0.8 0.3]


In [16]:
# Question 2

a = np.array([1 , 2 , 3])
b = np.array([4 , 5 , 6])
sum = a+b

print(sum)

[5 7 9]


In [20]:
# Question 3

a = 1.5
v = np.array([75 , 38 , 97 , 54])

scalar_product = a*v
print(scalar_product)

[112.5  57.  145.5  81. ]


In [18]:
#Question 4

concentration = np.array([0.5 , 1.2 , 0.8 , 0.3])
temperature = np.array([300 , 310 , 290 , 295])

dot_product = np.dot(concentration , temperature)

print(dot_product)

842.5


In [9]:
#Question 5
a = np.array([0.5 , 1.2 , 0.8 , 0.3])
norm = np.linalg.norm(a)

print(norm)

1.5556349186104046


In [19]:
#Question 6
a = np.array([1 , 2 , 3 , 4 , 5])
a_squared = np.square(a)

norm = np.sqrt(np.sum(a_squared))

print(norm)

7.416198487095663


In [21]:
#Question 7 

zeros = np.zeros(10)
zeros[4] = 25.0

print(zeros)

[ 0.  0.  0.  0. 25.  0.  0.  0.  0.  0.]


In [24]:
#Question 8

a = np.array([10 , 12 , 15 , 14 , 17])
b = np.array([15 , 22 , 32 , 18 , 16])

print(b - a)

[ 5 10 17  4 -1]


In [32]:
#Question 9

D = np.random.randint(0 , 100 , size=(3 , 4))
print(D)

[[11 98 46 59]
 [ 5 86 11 14]
 [68 42 70 51]]


In [34]:
#Question 10

print(D.shape)

(3, 4)


In [35]:
#Question 11

print(D.T)

[[11  5 68]
 [98 86 42]
 [46 11 70]
 [59 14 51]]


In [36]:
#Question 12

identity = np.identity(4)
print(identity)

[[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]


In [88]:
#Question 13

data_matrix = np.random.randint(0 , 100 , size=(3 , 4))
weights = np.random.uniform(0 , 1 , size=(4 , 2))

product = np.dot(data_matrix,weights)
print(product)

[[ 80.34944231 159.10855782]
 [ 90.28571459 174.99083748]
 [ 19.35142575  31.20289793]]


In [39]:
#Question 14
D = np.random.randint(0 , 100 , size=(3 , 4))
square_submatrix = D[: , :3]
print(square_submatrix)

[[25 90 60]
 [37  6 92]
 [ 6 75  5]]


In [40]:
#Question 15

arr = np.random.randint(0 , 100 , size=(3 , 3))
arr_inverse = np.linalg.inv(arr)

print(arr_inverse)

[[ 0.02935185 -0.04361111  0.02416667]
 [-0.00699805  0.02567251 -0.0145614 ]
 [-0.02276803  0.02502924 -0.00280702]]


In [43]:
#Question 16

A = np.random.randint(0 , 100 , size=(3 ,3))
A_inverse = np.linalg.inv(A)

print(np.round(A @ A_inverse))
print("Hence Proved.")

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]
Hence Proved.


In [66]:
#Question 17

A = np.array([
    [2.0, 0.8, 0.5],
    [0.8, 1.5, 0.3],
    [0.5, 0.3, 1.0]
])

eigenvalues , eigenvectors = np.linalg.eig(A)
print(eigenvalues)
print(eigenvectors)

[2.77789182 0.78863608 0.9334721 ]
[[-0.77116542 -0.45769801  0.44251149]
 [-0.55570103  0.14477233 -0.81868024]
 [-0.3106449   0.87724199  0.36598667]]


In [52]:
#Question 18

A = np.array([
    [2.0, 0.8, 0.5],
    [0.8, 1.5, 0.3],
    [0.5, 0.3, 1.0]
])

eigenvalues , eigenvectors = np.linalg.eig(A)

B = np.array(eigenvectors)
B_inverse = np.linalg.inv(B)
diagonal_matrix = np.diag(eigenvalues)

A_reconstructed = np.round(B @ diagonal_matrix @ B_inverse , 2)

print(A_reconstructed)
print("Eigen Decomposition Completed")
print(f"Eigen Values: {eigenvalues}")

[[2.  0.8 0.5]
 [0.8 1.5 0.3]
 [0.5 0.3 1. ]]
Eigen Decomposition Completed
Eigen Values: [2.77789182 0.78863608 0.9334721 ]


In [53]:
#Question 19

print(eigenvectors[: , 1])

[-0.55570103  0.14477233 -0.81868024]


In [54]:
#Question 20

sorted_indices = eigenvalues.argsort()
print(sorted_indices)

[1 2 0]


In [55]:
#Question 21

reversed_indices = sorted_indices[::-1]
print(reversed_indices)

[0 2 1]


In [56]:
#Question 22

print(eigenvalues[sorted_indices])

[0.78863608 0.9334721  2.77789182]


In [67]:
#Question 23

print(eigenvectors[: , sorted_indices])

[[-0.45769801  0.44251149 -0.77116542]
 [ 0.14477233 -0.81868024 -0.55570103]
 [ 0.87724199  0.36598667 -0.3106449 ]]


In [61]:
#Question 24

import math as m
def function(x , y):
    return x**2*y + m.sin(x)



In [62]:
#Question 25

def analytical_gradient(x , y):
    return np.array([2*x*y + m.cos(x) , x**2])
    

In [65]:
#Question 26

gradient = analytical_gradient(0, 1)
print(gradient)

[1. 0.]


In [69]:
#Question 27

def numerical_gradient(x , y , h=10**-5):
    return (function(x+h , y) - function(x , y)) / h

print(numerical_gradient(1 , 2))

4.54031809851152


In [81]:
#Question 28
def gradient_descent(x , n=0.1):
    gradient_function = x**2 + 2*x + 4
    gradient_function_derivative = 2*x + 2
    x_new = x - n*gradient_function_derivative
    return x_new

print(gradient_descent(0))

-0.2


In [87]:
#Question 30

def gradient_descent(x , n=0.1):
    history = []

    for i in range(10):
        gradient_function_derivative = 2*x - 6
        x_new = x - n*gradient_function_derivative
        x = x_new
        history.append(x)

    return history , x

print(gradient_descent(0))

        

([0.6000000000000001, 1.08, 1.464, 1.7711999999999999, 2.01696, 2.213568, 2.3708544, 2.49668352, 2.597346816, 2.6778774528], 2.6778774528)
